name: issues

on:
  issues:
    types: [opened, labeled]

jobs:
  welcome:
    name: Welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: Create Welcome Comment
        uses: shaodahong/github-action/create-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.issue.number }}
          comment: >
            Hey @${{ github.event.issue.user.login }}!
